name: aradeepopsis-dpp
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.7
  - conda-forge::pip=21.1.1
  - pip:
    - opencv-python-headless==4.5.2.52
    - https://github.com/p2irc/deepplantphenomics/archive/2.1.0.tar.gz