name: Docker build (Shiny dependencies)

on:
  push:
    paths:
      - 'containers/shiny/Dockerfile'
      - 'containers/shiny/environment.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        if: success()
        run: docker build -t beckerlab/aradeepopsis-shiny:${IMAGE_TAG} containers/shiny/

      - name: Push to Dockerhub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push beckerlab/aradeepopsis-shiny:${IMAGE_TAG}