name: Docker build

on:
   push:
     branches:
      - master
     tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 

      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        if: success()
        run: docker build -t beckerlab/aradeepopsis:${IMAGE_TAG} .

      - name: Push to Dockerhub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push beckerlab/aradeepopsis:${IMAGE_TAG}
