name: Integration test
on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches-ignore:
      - master

jobs:
  CI:
    env:
      PROFILE: ${{ matrix.engine }}
      NXF_VER: ${{ matrix.nxf_ver }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        engine: ["docker", "podman", "charliecloud", "conda"]
        nxf_ver: ["21.04.0", ""]
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        if: ${{ matrix.engine == 'charliecloud' && matrix.os == 'ubuntu-latest' }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Charliecloud
        if: ${{ matrix.engine == 'charliecloud' && matrix.os == 'ubuntu-latest' }}
        run: |
          python -m pip install lark-parser requests
          wget -qO- https://github.com/hpc/charliecloud/releases/download/v0.22/charliecloud-0.22.tar.gz | tar -xvz
          cd charliecloud-0.22
          ./configure
          make
          sudo make install

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run ARADEEPOPSIS
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} --save_rosette --save_histogram --save_hull --summary_diagnostics --shiny false -profile test,${PROFILE}

      - name: Run ARADEEPOPSIS
        if: ${{ matrix.os == 'macos-latest' && matrix.engine == 'conda' }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} --save_rosette --save_histogram --save_hull --summary_diagnostics --shiny false -profile test,${PROFILE}
