name: Integration test
on:
  push:
    branches-ignore:
      - master
      - dev    
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ["20.01.0", ""]
    steps:
      - uses: actions/checkout@v2

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run aradeepopsis on test images
        run: |
          nextflow run ${GITHUB_WORKSPACE} --save_rosette --save_histogram --save_hull -profile test,docker
